POST http://localhost:5000/api/authorize/signup
Content-Type: application/json

{
    "username": "Thanh Truc",
    "password": "MinhBao",
    "gmail": "Minhbaodinh0808@gmail.com",
    "sex": "female"
}


###


POST http://localhost:5000/api/authorize/login
Content-Type: application/json

{
    "username": "Thanh Truc",
    "password": "MinhBao"
}


###


GET http://localhost:5000/api/getSomeInformation
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzgxNTUzMjcsImV4cCI6MTYzODE1NTM1Mn0.2UvCvQGHyRTpMbH6u4Nju8BDO8S4ajG7BsB1c7eY-Cw


###


POST http://localhost:5000/api/authorize/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzgxNTUyOTEsImV4cCI6MTYzODE1ODg5MX0.UhvQJvNzPIkAFtO98QI3phK4N4X6loo-fdj8jGJw3ak"
}


###


DELETE http://localhost:5000/api/authorize/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTQ0MTU2ZjAwYzE0N2NmY2VhOWM1ZSIsInVzZXJuYW1lIjoiVGhhbmggVHJ1YyIsImlhdCI6MTYzODE1NjU5MywiZXhwIjoxNjM4MTYwMTkzfQ.jHkrzRNbKsZD0ru1XlsUOf8AB9eI-Ksy8j11cbxz7fo