POST http://localhost:5000/api/authorize/signup
Content-Type: application/json

{
    "username": "Thanh Truc cute",
    "password": "MinhBao",
    "gmail": "Minhbaodinh0808@gmail.com",
    "phoneNumber": "0832408762",
    "fullname": "Dinh Minh Bao"
}


###


POST http://localhost:5000/api/authorize/login
Content-Type: application/json

{
    "username": "Thanh Truc",
    "password": "MinhBao"
}



###


POST http://localhost:5000/api/authorize/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYTYxZmMwMDVhMzQxMzcyMjlhOTQwOCIsInVzZXJuYW1lIjoiVGhhbmggVHJ1YyIsImlhdCI6MTYzODI4NDA4NiwiZXhwIjoxNjM4Mjg3Njg2fQ.e_vD8hrsNOHs-giPnUU3bVStbb1pxguRpUhvqv_EnO0"
}


###


DELETE http://localhost:5000/api/authorize/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzgyODQxMTAsImV4cCI6MTYzODI4NzcxMH0.zkqrSuTxMkD7y_FCzHA6yOvo6D4x2zmq1Gef7-dif7M


###

POST http://localhost:5001/api/document/upload


###

GET http://localhost:5001/api/document/download


###

POST http://localhost:5000/profile